/*
 * WebApi.Frontend
 * WebApi.Frontend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Generatot.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets LoadMarkets
 */
@JsonAdapter(LoadMarkets.Adapter.class)
public enum LoadMarkets {
  
  All(0),
  
  HeaderMarkets(1),
  
  FirstHeader(2),
  
  CommonHeaders(3),
  
  None(4),
  
  Outrights(5);

  private Integer value;

  LoadMarkets(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LoadMarkets fromValue(Integer value) {
    for (LoadMarkets b : LoadMarkets.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<LoadMarkets> {
    @Override
    public void write(final JsonWriter jsonWriter, final LoadMarkets enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LoadMarkets read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return LoadMarkets.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    Integer value = jsonElement.getAsInt();
    LoadMarkets.fromValue(value);
  }
}

