/*
 * WebApi.Frontend
 * WebApi.Frontend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Generatot.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets MarketGroupTypes
 */
@JsonAdapter(MarketGroupTypes.Adapter.class)
public enum MarketGroupTypes {
  
  Common(0),
  
  OneMinute(1),
  
  FastMarkets(2),
  
  BetBuilder(3),
  
  Forcast(4),
  
  Tricast(5),
  
  Insights(6),
  
  HorseRacingPlace(7),
  
  Boost(8);

  private Integer value;

  MarketGroupTypes(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MarketGroupTypes fromValue(Integer value) {
    for (MarketGroupTypes b : MarketGroupTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MarketGroupTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final MarketGroupTypes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MarketGroupTypes read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return MarketGroupTypes.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    Integer value = jsonElement.getAsInt();
    MarketGroupTypes.fromValue(value);
  }
}

