/*
 * WebApi.Frontend
 * WebApi.Frontend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Generatot.model;

import Generatot.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Pitcher
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-25T19:49:20.010092+03:00[Europe/Moscow]")
public class Pitcher {
  public static final String SERIALIZED_NAME_COMPETITOR_ID = "CompetitorId";
  @SerializedName(SERIALIZED_NAME_COMPETITOR_ID)
  private Long competitorId;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_HAND = "Hand";
  @SerializedName(SERIALIZED_NAME_HAND)
  private String hand;

  public Pitcher() {
  }

  public Pitcher competitorId(Long competitorId) {
    this.competitorId = competitorId;
    return this;
  }

   /**
   * Get competitorId
   * @return competitorId
  **/
  @javax.annotation.Nonnull
  public Long getCompetitorId() {
    return competitorId;
  }

  public void setCompetitorId(Long competitorId) {
    this.competitorId = competitorId;
  }


  public Pitcher name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public Pitcher hand(String hand) {
    this.hand = hand;
    return this;
  }

   /**
   * Get hand
   * @return hand
  **/
  @javax.annotation.Nonnull
  public String getHand() {
    return hand;
  }

  public void setHand(String hand) {
    this.hand = hand;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pitcher pitcher = (Pitcher) o;
    return Objects.equals(this.competitorId, pitcher.competitorId) &&
        Objects.equals(this.name, pitcher.name) &&
        Objects.equals(this.hand, pitcher.hand);
  }

  @Override
  public int hashCode() {
    return Objects.hash(competitorId, name, hand);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pitcher {\n");
    sb.append("    competitorId: ").append(toIndentedString(competitorId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    hand: ").append(toIndentedString(hand)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CompetitorId");
    openapiFields.add("Name");
    openapiFields.add("Hand");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("CompetitorId");
    openapiRequiredFields.add("Name");
    openapiRequiredFields.add("Hand");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Pitcher
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Pitcher.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Pitcher is not found in the empty JSON string", Pitcher.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Pitcher.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Pitcher` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Pitcher.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("Name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Name").toString()));
      }
      if (!jsonObj.get("Hand").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Hand` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Hand").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Pitcher.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Pitcher' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Pitcher> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Pitcher.class));

       return (TypeAdapter<T>) new TypeAdapter<Pitcher>() {
           @Override
           public void write(JsonWriter out, Pitcher value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Pitcher read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Pitcher given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Pitcher
  * @throws IOException if the JSON string is invalid with respect to Pitcher
  */
  public static Pitcher fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Pitcher.class);
  }

 /**
  * Convert an instance of Pitcher to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

