/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * AamsFlowBetPaymentRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class AamsFlowBetPaymentRequest {
  public static final String SERIALIZED_NAME_BET_IDS = "BetIds";
  @SerializedName(SERIALIZED_NAME_BET_IDS)
  private List<Long> betIds;

  public AamsFlowBetPaymentRequest() {
  }

  public AamsFlowBetPaymentRequest betIds(List<Long> betIds) {
    this.betIds = betIds;
    return this;
  }

  public AamsFlowBetPaymentRequest addBetIdsItem(Long betIdsItem) {
    if (this.betIds == null) {
      this.betIds = new ArrayList<>();
    }
    this.betIds.add(betIdsItem);
    return this;
  }

   /**
   * Get betIds
   * @return betIds
  **/
  @javax.annotation.Nullable
  public List<Long> getBetIds() {
    return betIds;
  }

  public void setBetIds(List<Long> betIds) {
    this.betIds = betIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AamsFlowBetPaymentRequest aamsFlowBetPaymentRequest = (AamsFlowBetPaymentRequest) o;
    return Objects.equals(this.betIds, aamsFlowBetPaymentRequest.betIds);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(betIds);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AamsFlowBetPaymentRequest {\n");
    sb.append("    betIds: ").append(toIndentedString(betIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("BetIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AamsFlowBetPaymentRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AamsFlowBetPaymentRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AamsFlowBetPaymentRequest is not found in the empty JSON string", AamsFlowBetPaymentRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AamsFlowBetPaymentRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AamsFlowBetPaymentRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("BetIds") != null && !jsonObj.get("BetIds").isJsonNull() && !jsonObj.get("BetIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `BetIds` to be an array in the JSON string but got `%s`", jsonObj.get("BetIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AamsFlowBetPaymentRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AamsFlowBetPaymentRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AamsFlowBetPaymentRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AamsFlowBetPaymentRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AamsFlowBetPaymentRequest>() {
           @Override
           public void write(JsonWriter out, AamsFlowBetPaymentRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AamsFlowBetPaymentRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AamsFlowBetPaymentRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AamsFlowBetPaymentRequest
  * @throws IOException if the JSON string is invalid with respect to AamsFlowBetPaymentRequest
  */
  public static AamsFlowBetPaymentRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AamsFlowBetPaymentRequest.class);
  }

 /**
  * Convert an instance of AamsFlowBetPaymentRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

