/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * AddConfigAttributeRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class AddConfigAttributeRequest {
  public static final String SERIALIZED_NAME_CONFIG_ATTRIBUTE_KEY = "ConfigAttributeKey";
  @SerializedName(SERIALIZED_NAME_CONFIG_ATTRIBUTE_KEY)
  private String configAttributeKey;

  public static final String SERIALIZED_NAME_CONFIG_ATTRIBUTE_VALUE = "ConfigAttributeValue";
  @SerializedName(SERIALIZED_NAME_CONFIG_ATTRIBUTE_VALUE)
  private String configAttributeValue;

  public static final String SERIALIZED_NAME_CONFIG_ID = "ConfigId";
  @SerializedName(SERIALIZED_NAME_CONFIG_ID)
  private Integer configId;

  public AddConfigAttributeRequest() {
  }

  public AddConfigAttributeRequest configAttributeKey(String configAttributeKey) {
    this.configAttributeKey = configAttributeKey;
    return this;
  }

   /**
   * Get configAttributeKey
   * @return configAttributeKey
  **/
  @javax.annotation.Nullable
  public String getConfigAttributeKey() {
    return configAttributeKey;
  }

  public void setConfigAttributeKey(String configAttributeKey) {
    this.configAttributeKey = configAttributeKey;
  }


  public AddConfigAttributeRequest configAttributeValue(String configAttributeValue) {
    this.configAttributeValue = configAttributeValue;
    return this;
  }

   /**
   * Get configAttributeValue
   * @return configAttributeValue
  **/
  @javax.annotation.Nullable
  public String getConfigAttributeValue() {
    return configAttributeValue;
  }

  public void setConfigAttributeValue(String configAttributeValue) {
    this.configAttributeValue = configAttributeValue;
  }


  public AddConfigAttributeRequest configId(Integer configId) {
    this.configId = configId;
    return this;
  }

   /**
   * Get configId
   * @return configId
  **/
  @javax.annotation.Nullable
  public Integer getConfigId() {
    return configId;
  }

  public void setConfigId(Integer configId) {
    this.configId = configId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddConfigAttributeRequest addConfigAttributeRequest = (AddConfigAttributeRequest) o;
    return Objects.equals(this.configAttributeKey, addConfigAttributeRequest.configAttributeKey) &&
        Objects.equals(this.configAttributeValue, addConfigAttributeRequest.configAttributeValue) &&
        Objects.equals(this.configId, addConfigAttributeRequest.configId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(configAttributeKey, configAttributeValue, configId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddConfigAttributeRequest {\n");
    sb.append("    configAttributeKey: ").append(toIndentedString(configAttributeKey)).append("\n");
    sb.append("    configAttributeValue: ").append(toIndentedString(configAttributeValue)).append("\n");
    sb.append("    configId: ").append(toIndentedString(configId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ConfigAttributeKey");
    openapiFields.add("ConfigAttributeValue");
    openapiFields.add("ConfigId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AddConfigAttributeRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AddConfigAttributeRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AddConfigAttributeRequest is not found in the empty JSON string", AddConfigAttributeRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AddConfigAttributeRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AddConfigAttributeRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("ConfigAttributeKey") != null && !jsonObj.get("ConfigAttributeKey").isJsonNull()) && !jsonObj.get("ConfigAttributeKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ConfigAttributeKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ConfigAttributeKey").toString()));
      }
      if ((jsonObj.get("ConfigAttributeValue") != null && !jsonObj.get("ConfigAttributeValue").isJsonNull()) && !jsonObj.get("ConfigAttributeValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ConfigAttributeValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ConfigAttributeValue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AddConfigAttributeRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AddConfigAttributeRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AddConfigAttributeRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AddConfigAttributeRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AddConfigAttributeRequest>() {
           @Override
           public void write(JsonWriter out, AddConfigAttributeRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AddConfigAttributeRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AddConfigAttributeRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AddConfigAttributeRequest
  * @throws IOException if the JSON string is invalid with respect to AddConfigAttributeRequest
  */
  public static AddConfigAttributeRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AddConfigAttributeRequest.class);
  }

 /**
  * Convert an instance of AddConfigAttributeRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

