/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * BonusTypesFilterItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class BonusTypesFilterItem {
  public static final String SERIALIZED_NAME_BONUS_TYPE_NAME = "BonusTypeName";
  @SerializedName(SERIALIZED_NAME_BONUS_TYPE_NAME)
  private String bonusTypeName;

  public static final String SERIALIZED_NAME_BONUS_TYPE_ID = "BonusTypeId";
  @SerializedName(SERIALIZED_NAME_BONUS_TYPE_ID)
  private BonusTypes bonusTypeId;

  public BonusTypesFilterItem() {
  }

  public BonusTypesFilterItem bonusTypeName(String bonusTypeName) {
    this.bonusTypeName = bonusTypeName;
    return this;
  }

   /**
   * Get bonusTypeName
   * @return bonusTypeName
  **/
  @javax.annotation.Nullable
  public String getBonusTypeName() {
    return bonusTypeName;
  }

  public void setBonusTypeName(String bonusTypeName) {
    this.bonusTypeName = bonusTypeName;
  }


  public BonusTypesFilterItem bonusTypeId(BonusTypes bonusTypeId) {
    this.bonusTypeId = bonusTypeId;
    return this;
  }

   /**
   * Get bonusTypeId
   * @return bonusTypeId
  **/
  @javax.annotation.Nullable
  public BonusTypes getBonusTypeId() {
    return bonusTypeId;
  }

  public void setBonusTypeId(BonusTypes bonusTypeId) {
    this.bonusTypeId = bonusTypeId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BonusTypesFilterItem bonusTypesFilterItem = (BonusTypesFilterItem) o;
    return Objects.equals(this.bonusTypeName, bonusTypesFilterItem.bonusTypeName) &&
        Objects.equals(this.bonusTypeId, bonusTypesFilterItem.bonusTypeId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(bonusTypeName, bonusTypeId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BonusTypesFilterItem {\n");
    sb.append("    bonusTypeName: ").append(toIndentedString(bonusTypeName)).append("\n");
    sb.append("    bonusTypeId: ").append(toIndentedString(bonusTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("BonusTypeName");
    openapiFields.add("BonusTypeId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BonusTypesFilterItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BonusTypesFilterItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BonusTypesFilterItem is not found in the empty JSON string", BonusTypesFilterItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BonusTypesFilterItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BonusTypesFilterItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("BonusTypeName") != null && !jsonObj.get("BonusTypeName").isJsonNull()) && !jsonObj.get("BonusTypeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `BonusTypeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("BonusTypeName").toString()));
      }
      // validate the optional field `BonusTypeId`
      if (jsonObj.get("BonusTypeId") != null && !jsonObj.get("BonusTypeId").isJsonNull()) {
        BonusTypes.validateJsonElement(jsonObj.get("BonusTypeId"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BonusTypesFilterItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BonusTypesFilterItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BonusTypesFilterItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BonusTypesFilterItem.class));

       return (TypeAdapter<T>) new TypeAdapter<BonusTypesFilterItem>() {
           @Override
           public void write(JsonWriter out, BonusTypesFilterItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BonusTypesFilterItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BonusTypesFilterItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BonusTypesFilterItem
  * @throws IOException if the JSON string is invalid with respect to BonusTypesFilterItem
  */
  public static BonusTypesFilterItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BonusTypesFilterItem.class);
  }

 /**
  * Convert an instance of BonusTypesFilterItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

