/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * BoostItemOdds
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class BoostItemOdds {
  public static final String SERIALIZED_NAME_FM_CONFIG_ID = "FMConfigId";
  @SerializedName(SERIALIZED_NAME_FM_CONFIG_ID)
  private Integer fmConfigId;

  public static final String SERIALIZED_NAME_EVENT_ID = "EventId";
  @SerializedName(SERIALIZED_NAME_EVENT_ID)
  private Long eventId;

  public static final String SERIALIZED_NAME_MARKET_TYPE_ID = "MarketTypeId";
  @SerializedName(SERIALIZED_NAME_MARKET_TYPE_ID)
  private Integer marketTypeId;

  public static final String SERIALIZED_NAME_SELECTION_TYPE_ID = "SelectionTypeId";
  @SerializedName(SERIALIZED_NAME_SELECTION_TYPE_ID)
  private Integer selectionTypeId;

  public static final String SERIALIZED_NAME_SPECIAL_ODDS_VALUE = "SpecialOddsValue";
  @SerializedName(SERIALIZED_NAME_SPECIAL_ODDS_VALUE)
  private String specialOddsValue;

  public static final String SERIALIZED_NAME_SELECTION_ID = "SelectionId";
  @SerializedName(SERIALIZED_NAME_SELECTION_ID)
  private Long selectionId;

  public static final String SERIALIZED_NAME_TRADING_CONFIG_NAME = "TradingConfigName";
  @SerializedName(SERIALIZED_NAME_TRADING_CONFIG_NAME)
  private String tradingConfigName;

  public static final String SERIALIZED_NAME_FEED_PROVIDER_NAME = "FeedProviderName";
  @SerializedName(SERIALIZED_NAME_FEED_PROVIDER_NAME)
  private String feedProviderName;

  public static final String SERIALIZED_NAME_FEED_PRICE = "FeedPrice";
  @SerializedName(SERIALIZED_NAME_FEED_PRICE)
  private Double feedPrice;

  public static final String SERIALIZED_NAME_BRAND_PRICE = "BrandPrice";
  @SerializedName(SERIALIZED_NAME_BRAND_PRICE)
  private Double brandPrice;

  public static final String SERIALIZED_NAME_BOOST_PRICE = "BoostPrice";
  @SerializedName(SERIALIZED_NAME_BOOST_PRICE)
  private Double boostPrice;

  public static final String SERIALIZED_NAME_IS_AUTO_UPDATE = "IsAutoUpdate";
  @SerializedName(SERIALIZED_NAME_IS_AUTO_UPDATE)
  private Boolean isAutoUpdate;

  public static final String SERIALIZED_NAME_BOOST_METHOD = "BoostMethod";
  @SerializedName(SERIALIZED_NAME_BOOST_METHOD)
  private BoostItemMethod boostMethod;

  public static final String SERIALIZED_NAME_BOOST_ITEM_ID = "BoostItemId";
  @SerializedName(SERIALIZED_NAME_BOOST_ITEM_ID)
  private Integer boostItemId;

  public BoostItemOdds() {
  }

  public BoostItemOdds fmConfigId(Integer fmConfigId) {
    this.fmConfigId = fmConfigId;
    return this;
  }

   /**
   * Get fmConfigId
   * @return fmConfigId
  **/
  @javax.annotation.Nullable
  public Integer getFmConfigId() {
    return fmConfigId;
  }

  public void setFmConfigId(Integer fmConfigId) {
    this.fmConfigId = fmConfigId;
  }


  public BoostItemOdds eventId(Long eventId) {
    this.eventId = eventId;
    return this;
  }

   /**
   * Get eventId
   * @return eventId
  **/
  @javax.annotation.Nullable
  public Long getEventId() {
    return eventId;
  }

  public void setEventId(Long eventId) {
    this.eventId = eventId;
  }


  public BoostItemOdds marketTypeId(Integer marketTypeId) {
    this.marketTypeId = marketTypeId;
    return this;
  }

   /**
   * Get marketTypeId
   * @return marketTypeId
  **/
  @javax.annotation.Nullable
  public Integer getMarketTypeId() {
    return marketTypeId;
  }

  public void setMarketTypeId(Integer marketTypeId) {
    this.marketTypeId = marketTypeId;
  }


  public BoostItemOdds selectionTypeId(Integer selectionTypeId) {
    this.selectionTypeId = selectionTypeId;
    return this;
  }

   /**
   * Get selectionTypeId
   * @return selectionTypeId
  **/
  @javax.annotation.Nullable
  public Integer getSelectionTypeId() {
    return selectionTypeId;
  }

  public void setSelectionTypeId(Integer selectionTypeId) {
    this.selectionTypeId = selectionTypeId;
  }


  public BoostItemOdds specialOddsValue(String specialOddsValue) {
    this.specialOddsValue = specialOddsValue;
    return this;
  }

   /**
   * Get specialOddsValue
   * @return specialOddsValue
  **/
  @javax.annotation.Nullable
  public String getSpecialOddsValue() {
    return specialOddsValue;
  }

  public void setSpecialOddsValue(String specialOddsValue) {
    this.specialOddsValue = specialOddsValue;
  }


  public BoostItemOdds selectionId(Long selectionId) {
    this.selectionId = selectionId;
    return this;
  }

   /**
   * Get selectionId
   * @return selectionId
  **/
  @javax.annotation.Nullable
  public Long getSelectionId() {
    return selectionId;
  }

  public void setSelectionId(Long selectionId) {
    this.selectionId = selectionId;
  }


  public BoostItemOdds tradingConfigName(String tradingConfigName) {
    this.tradingConfigName = tradingConfigName;
    return this;
  }

   /**
   * Get tradingConfigName
   * @return tradingConfigName
  **/
  @javax.annotation.Nullable
  public String getTradingConfigName() {
    return tradingConfigName;
  }

  public void setTradingConfigName(String tradingConfigName) {
    this.tradingConfigName = tradingConfigName;
  }


  public BoostItemOdds feedProviderName(String feedProviderName) {
    this.feedProviderName = feedProviderName;
    return this;
  }

   /**
   * Get feedProviderName
   * @return feedProviderName
  **/
  @javax.annotation.Nullable
  public String getFeedProviderName() {
    return feedProviderName;
  }

  public void setFeedProviderName(String feedProviderName) {
    this.feedProviderName = feedProviderName;
  }


  public BoostItemOdds feedPrice(Double feedPrice) {
    this.feedPrice = feedPrice;
    return this;
  }

   /**
   * Get feedPrice
   * @return feedPrice
  **/
  @javax.annotation.Nullable
  public Double getFeedPrice() {
    return feedPrice;
  }

  public void setFeedPrice(Double feedPrice) {
    this.feedPrice = feedPrice;
  }


  public BoostItemOdds brandPrice(Double brandPrice) {
    this.brandPrice = brandPrice;
    return this;
  }

   /**
   * Get brandPrice
   * @return brandPrice
  **/
  @javax.annotation.Nullable
  public Double getBrandPrice() {
    return brandPrice;
  }

  public void setBrandPrice(Double brandPrice) {
    this.brandPrice = brandPrice;
  }


  public BoostItemOdds boostPrice(Double boostPrice) {
    this.boostPrice = boostPrice;
    return this;
  }

   /**
   * Get boostPrice
   * @return boostPrice
  **/
  @javax.annotation.Nullable
  public Double getBoostPrice() {
    return boostPrice;
  }

  public void setBoostPrice(Double boostPrice) {
    this.boostPrice = boostPrice;
  }


  public BoostItemOdds isAutoUpdate(Boolean isAutoUpdate) {
    this.isAutoUpdate = isAutoUpdate;
    return this;
  }

   /**
   * Get isAutoUpdate
   * @return isAutoUpdate
  **/
  @javax.annotation.Nullable
  public Boolean getIsAutoUpdate() {
    return isAutoUpdate;
  }

  public void setIsAutoUpdate(Boolean isAutoUpdate) {
    this.isAutoUpdate = isAutoUpdate;
  }


  public BoostItemOdds boostMethod(BoostItemMethod boostMethod) {
    this.boostMethod = boostMethod;
    return this;
  }

   /**
   * Get boostMethod
   * @return boostMethod
  **/
  @javax.annotation.Nullable
  public BoostItemMethod getBoostMethod() {
    return boostMethod;
  }

  public void setBoostMethod(BoostItemMethod boostMethod) {
    this.boostMethod = boostMethod;
  }


  public BoostItemOdds boostItemId(Integer boostItemId) {
    this.boostItemId = boostItemId;
    return this;
  }

   /**
   * Get boostItemId
   * @return boostItemId
  **/
  @javax.annotation.Nullable
  public Integer getBoostItemId() {
    return boostItemId;
  }

  public void setBoostItemId(Integer boostItemId) {
    this.boostItemId = boostItemId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoostItemOdds boostItemOdds = (BoostItemOdds) o;
    return Objects.equals(this.fmConfigId, boostItemOdds.fmConfigId) &&
        Objects.equals(this.eventId, boostItemOdds.eventId) &&
        Objects.equals(this.marketTypeId, boostItemOdds.marketTypeId) &&
        Objects.equals(this.selectionTypeId, boostItemOdds.selectionTypeId) &&
        Objects.equals(this.specialOddsValue, boostItemOdds.specialOddsValue) &&
        Objects.equals(this.selectionId, boostItemOdds.selectionId) &&
        Objects.equals(this.tradingConfigName, boostItemOdds.tradingConfigName) &&
        Objects.equals(this.feedProviderName, boostItemOdds.feedProviderName) &&
        Objects.equals(this.feedPrice, boostItemOdds.feedPrice) &&
        Objects.equals(this.brandPrice, boostItemOdds.brandPrice) &&
        Objects.equals(this.boostPrice, boostItemOdds.boostPrice) &&
        Objects.equals(this.isAutoUpdate, boostItemOdds.isAutoUpdate) &&
        Objects.equals(this.boostMethod, boostItemOdds.boostMethod) &&
        Objects.equals(this.boostItemId, boostItemOdds.boostItemId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(fmConfigId, eventId, marketTypeId, selectionTypeId, specialOddsValue, selectionId, tradingConfigName, feedProviderName, feedPrice, brandPrice, boostPrice, isAutoUpdate, boostMethod, boostItemId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoostItemOdds {\n");
    sb.append("    fmConfigId: ").append(toIndentedString(fmConfigId)).append("\n");
    sb.append("    eventId: ").append(toIndentedString(eventId)).append("\n");
    sb.append("    marketTypeId: ").append(toIndentedString(marketTypeId)).append("\n");
    sb.append("    selectionTypeId: ").append(toIndentedString(selectionTypeId)).append("\n");
    sb.append("    specialOddsValue: ").append(toIndentedString(specialOddsValue)).append("\n");
    sb.append("    selectionId: ").append(toIndentedString(selectionId)).append("\n");
    sb.append("    tradingConfigName: ").append(toIndentedString(tradingConfigName)).append("\n");
    sb.append("    feedProviderName: ").append(toIndentedString(feedProviderName)).append("\n");
    sb.append("    feedPrice: ").append(toIndentedString(feedPrice)).append("\n");
    sb.append("    brandPrice: ").append(toIndentedString(brandPrice)).append("\n");
    sb.append("    boostPrice: ").append(toIndentedString(boostPrice)).append("\n");
    sb.append("    isAutoUpdate: ").append(toIndentedString(isAutoUpdate)).append("\n");
    sb.append("    boostMethod: ").append(toIndentedString(boostMethod)).append("\n");
    sb.append("    boostItemId: ").append(toIndentedString(boostItemId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("FMConfigId");
    openapiFields.add("EventId");
    openapiFields.add("MarketTypeId");
    openapiFields.add("SelectionTypeId");
    openapiFields.add("SpecialOddsValue");
    openapiFields.add("SelectionId");
    openapiFields.add("TradingConfigName");
    openapiFields.add("FeedProviderName");
    openapiFields.add("FeedPrice");
    openapiFields.add("BrandPrice");
    openapiFields.add("BoostPrice");
    openapiFields.add("IsAutoUpdate");
    openapiFields.add("BoostMethod");
    openapiFields.add("BoostItemId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BoostItemOdds
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BoostItemOdds.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BoostItemOdds is not found in the empty JSON string", BoostItemOdds.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BoostItemOdds.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BoostItemOdds` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("SpecialOddsValue") != null && !jsonObj.get("SpecialOddsValue").isJsonNull()) && !jsonObj.get("SpecialOddsValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `SpecialOddsValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("SpecialOddsValue").toString()));
      }
      if ((jsonObj.get("TradingConfigName") != null && !jsonObj.get("TradingConfigName").isJsonNull()) && !jsonObj.get("TradingConfigName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `TradingConfigName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("TradingConfigName").toString()));
      }
      if ((jsonObj.get("FeedProviderName") != null && !jsonObj.get("FeedProviderName").isJsonNull()) && !jsonObj.get("FeedProviderName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `FeedProviderName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("FeedProviderName").toString()));
      }
      // validate the optional field `BoostMethod`
      if (jsonObj.get("BoostMethod") != null && !jsonObj.get("BoostMethod").isJsonNull()) {
        BoostItemMethod.validateJsonElement(jsonObj.get("BoostMethod"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BoostItemOdds.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BoostItemOdds' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BoostItemOdds> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BoostItemOdds.class));

       return (TypeAdapter<T>) new TypeAdapter<BoostItemOdds>() {
           @Override
           public void write(JsonWriter out, BoostItemOdds value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BoostItemOdds read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BoostItemOdds given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BoostItemOdds
  * @throws IOException if the JSON string is invalid with respect to BoostItemOdds
  */
  public static BoostItemOdds fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BoostItemOdds.class);
  }

 /**
  * Convert an instance of BoostItemOdds to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

