/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * ChangeOutrightGroupsTopDisplayOrderRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class ChangeOutrightGroupsTopDisplayOrderRequest {
  public static final String SERIALIZED_NAME_GROUPS = "Groups";
  @SerializedName(SERIALIZED_NAME_GROUPS)
  private List<TopGroupRequestItem> groups;

  public ChangeOutrightGroupsTopDisplayOrderRequest() {
  }

  public ChangeOutrightGroupsTopDisplayOrderRequest groups(List<TopGroupRequestItem> groups) {
    this.groups = groups;
    return this;
  }

  public ChangeOutrightGroupsTopDisplayOrderRequest addGroupsItem(TopGroupRequestItem groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @javax.annotation.Nullable
  public List<TopGroupRequestItem> getGroups() {
    return groups;
  }

  public void setGroups(List<TopGroupRequestItem> groups) {
    this.groups = groups;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeOutrightGroupsTopDisplayOrderRequest changeOutrightGroupsTopDisplayOrderRequest = (ChangeOutrightGroupsTopDisplayOrderRequest) o;
    return Objects.equals(this.groups, changeOutrightGroupsTopDisplayOrderRequest.groups);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(groups);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangeOutrightGroupsTopDisplayOrderRequest {\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Groups");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ChangeOutrightGroupsTopDisplayOrderRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChangeOutrightGroupsTopDisplayOrderRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChangeOutrightGroupsTopDisplayOrderRequest is not found in the empty JSON string", ChangeOutrightGroupsTopDisplayOrderRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChangeOutrightGroupsTopDisplayOrderRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChangeOutrightGroupsTopDisplayOrderRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("Groups") != null && !jsonObj.get("Groups").isJsonNull()) {
        JsonArray jsonArraygroups = jsonObj.getAsJsonArray("Groups");
        if (jsonArraygroups != null) {
          // ensure the json data is an array
          if (!jsonObj.get("Groups").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `Groups` to be an array in the JSON string but got `%s`", jsonObj.get("Groups").toString()));
          }

          // validate the optional field `Groups` (array)
          for (int i = 0; i < jsonArraygroups.size(); i++) {
            TopGroupRequestItem.validateJsonElement(jsonArraygroups.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChangeOutrightGroupsTopDisplayOrderRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChangeOutrightGroupsTopDisplayOrderRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChangeOutrightGroupsTopDisplayOrderRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChangeOutrightGroupsTopDisplayOrderRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ChangeOutrightGroupsTopDisplayOrderRequest>() {
           @Override
           public void write(JsonWriter out, ChangeOutrightGroupsTopDisplayOrderRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChangeOutrightGroupsTopDisplayOrderRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ChangeOutrightGroupsTopDisplayOrderRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChangeOutrightGroupsTopDisplayOrderRequest
  * @throws IOException if the JSON string is invalid with respect to ChangeOutrightGroupsTopDisplayOrderRequest
  */
  public static ChangeOutrightGroupsTopDisplayOrderRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChangeOutrightGroupsTopDisplayOrderRequest.class);
  }

 /**
  * Convert an instance of ChangeOutrightGroupsTopDisplayOrderRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

