/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * CreateConfigBoostTemplateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class CreateConfigBoostTemplateRequest {
  public static final String SERIALIZED_NAME_SPORT_ID = "SportId";
  @SerializedName(SERIALIZED_NAME_SPORT_ID)
  private Integer sportId;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SOURCE_TEMPLATE_ID = "SourceTemplateId";
  @SerializedName(SERIALIZED_NAME_SOURCE_TEMPLATE_ID)
  private Integer sourceTemplateId;

  public static final String SERIALIZED_NAME_LADDER_TYPE_ID = "LadderTypeId";
  @SerializedName(SERIALIZED_NAME_LADDER_TYPE_ID)
  private LadderTypes ladderTypeId;

  public static final String SERIALIZED_NAME_IS_LIVE = "IsLive";
  @SerializedName(SERIALIZED_NAME_IS_LIVE)
  private Boolean isLive;

  public static final String SERIALIZED_NAME_OFFER_START_TIME = "OfferStartTime";
  @SerializedName(SERIALIZED_NAME_OFFER_START_TIME)
  private Integer offerStartTime;

  public static final String SERIALIZED_NAME_GENERATION_TIME = "GenerationTime";
  @SerializedName(SERIALIZED_NAME_GENERATION_TIME)
  private Integer generationTime;

  public static final String SERIALIZED_NAME_IS_ENABLED = "IsEnabled";
  @SerializedName(SERIALIZED_NAME_IS_ENABLED)
  private Boolean isEnabled;

  public static final String SERIALIZED_NAME_CONFIG_ID = "ConfigId";
  @SerializedName(SERIALIZED_NAME_CONFIG_ID)
  private Integer configId;

  public CreateConfigBoostTemplateRequest() {
  }

  public CreateConfigBoostTemplateRequest sportId(Integer sportId) {
    this.sportId = sportId;
    return this;
  }

   /**
   * Get sportId
   * @return sportId
  **/
  @javax.annotation.Nullable
  public Integer getSportId() {
    return sportId;
  }

  public void setSportId(Integer sportId) {
    this.sportId = sportId;
  }


  public CreateConfigBoostTemplateRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public CreateConfigBoostTemplateRequest sourceTemplateId(Integer sourceTemplateId) {
    this.sourceTemplateId = sourceTemplateId;
    return this;
  }

   /**
   * Get sourceTemplateId
   * @return sourceTemplateId
  **/
  @javax.annotation.Nullable
  public Integer getSourceTemplateId() {
    return sourceTemplateId;
  }

  public void setSourceTemplateId(Integer sourceTemplateId) {
    this.sourceTemplateId = sourceTemplateId;
  }


  public CreateConfigBoostTemplateRequest ladderTypeId(LadderTypes ladderTypeId) {
    this.ladderTypeId = ladderTypeId;
    return this;
  }

   /**
   * Get ladderTypeId
   * @return ladderTypeId
  **/
  @javax.annotation.Nullable
  public LadderTypes getLadderTypeId() {
    return ladderTypeId;
  }

  public void setLadderTypeId(LadderTypes ladderTypeId) {
    this.ladderTypeId = ladderTypeId;
  }


  public CreateConfigBoostTemplateRequest isLive(Boolean isLive) {
    this.isLive = isLive;
    return this;
  }

   /**
   * Get isLive
   * @return isLive
  **/
  @javax.annotation.Nullable
  public Boolean getIsLive() {
    return isLive;
  }

  public void setIsLive(Boolean isLive) {
    this.isLive = isLive;
  }


  public CreateConfigBoostTemplateRequest offerStartTime(Integer offerStartTime) {
    this.offerStartTime = offerStartTime;
    return this;
  }

   /**
   * Get offerStartTime
   * @return offerStartTime
  **/
  @javax.annotation.Nullable
  public Integer getOfferStartTime() {
    return offerStartTime;
  }

  public void setOfferStartTime(Integer offerStartTime) {
    this.offerStartTime = offerStartTime;
  }


  public CreateConfigBoostTemplateRequest generationTime(Integer generationTime) {
    this.generationTime = generationTime;
    return this;
  }

   /**
   * Get generationTime
   * @return generationTime
  **/
  @javax.annotation.Nullable
  public Integer getGenerationTime() {
    return generationTime;
  }

  public void setGenerationTime(Integer generationTime) {
    this.generationTime = generationTime;
  }


  public CreateConfigBoostTemplateRequest isEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * Get isEnabled
   * @return isEnabled
  **/
  @javax.annotation.Nullable
  public Boolean getIsEnabled() {
    return isEnabled;
  }

  public void setIsEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }


  public CreateConfigBoostTemplateRequest configId(Integer configId) {
    this.configId = configId;
    return this;
  }

   /**
   * Get configId
   * @return configId
  **/
  @javax.annotation.Nullable
  public Integer getConfigId() {
    return configId;
  }

  public void setConfigId(Integer configId) {
    this.configId = configId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateConfigBoostTemplateRequest createConfigBoostTemplateRequest = (CreateConfigBoostTemplateRequest) o;
    return Objects.equals(this.sportId, createConfigBoostTemplateRequest.sportId) &&
        Objects.equals(this.name, createConfigBoostTemplateRequest.name) &&
        Objects.equals(this.sourceTemplateId, createConfigBoostTemplateRequest.sourceTemplateId) &&
        Objects.equals(this.ladderTypeId, createConfigBoostTemplateRequest.ladderTypeId) &&
        Objects.equals(this.isLive, createConfigBoostTemplateRequest.isLive) &&
        Objects.equals(this.offerStartTime, createConfigBoostTemplateRequest.offerStartTime) &&
        Objects.equals(this.generationTime, createConfigBoostTemplateRequest.generationTime) &&
        Objects.equals(this.isEnabled, createConfigBoostTemplateRequest.isEnabled) &&
        Objects.equals(this.configId, createConfigBoostTemplateRequest.configId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(sportId, name, sourceTemplateId, ladderTypeId, isLive, offerStartTime, generationTime, isEnabled, configId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateConfigBoostTemplateRequest {\n");
    sb.append("    sportId: ").append(toIndentedString(sportId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sourceTemplateId: ").append(toIndentedString(sourceTemplateId)).append("\n");
    sb.append("    ladderTypeId: ").append(toIndentedString(ladderTypeId)).append("\n");
    sb.append("    isLive: ").append(toIndentedString(isLive)).append("\n");
    sb.append("    offerStartTime: ").append(toIndentedString(offerStartTime)).append("\n");
    sb.append("    generationTime: ").append(toIndentedString(generationTime)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    configId: ").append(toIndentedString(configId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("SportId");
    openapiFields.add("Name");
    openapiFields.add("SourceTemplateId");
    openapiFields.add("LadderTypeId");
    openapiFields.add("IsLive");
    openapiFields.add("OfferStartTime");
    openapiFields.add("GenerationTime");
    openapiFields.add("IsEnabled");
    openapiFields.add("ConfigId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CreateConfigBoostTemplateRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateConfigBoostTemplateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateConfigBoostTemplateRequest is not found in the empty JSON string", CreateConfigBoostTemplateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateConfigBoostTemplateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateConfigBoostTemplateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) && !jsonObj.get("Name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Name").toString()));
      }
      // validate the optional field `LadderTypeId`
      if (jsonObj.get("LadderTypeId") != null && !jsonObj.get("LadderTypeId").isJsonNull()) {
        LadderTypes.validateJsonElement(jsonObj.get("LadderTypeId"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateConfigBoostTemplateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateConfigBoostTemplateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateConfigBoostTemplateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateConfigBoostTemplateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateConfigBoostTemplateRequest>() {
           @Override
           public void write(JsonWriter out, CreateConfigBoostTemplateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateConfigBoostTemplateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateConfigBoostTemplateRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateConfigBoostTemplateRequest
  * @throws IOException if the JSON string is invalid with respect to CreateConfigBoostTemplateRequest
  */
  public static CreateConfigBoostTemplateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateConfigBoostTemplateRequest.class);
  }

 /**
  * Convert an instance of CreateConfigBoostTemplateRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

