/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * DeleteFeedManagerTemplateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class DeleteFeedManagerTemplateRequest {
  public static final String SERIALIZED_NAME_FEED_TEMPLATE_ID = "FeedTemplateId";
  @SerializedName(SERIALIZED_NAME_FEED_TEMPLATE_ID)
  private Integer feedTemplateId;

  public DeleteFeedManagerTemplateRequest() {
  }

  public DeleteFeedManagerTemplateRequest feedTemplateId(Integer feedTemplateId) {
    this.feedTemplateId = feedTemplateId;
    return this;
  }

   /**
   * Get feedTemplateId
   * @return feedTemplateId
  **/
  @javax.annotation.Nullable
  public Integer getFeedTemplateId() {
    return feedTemplateId;
  }

  public void setFeedTemplateId(Integer feedTemplateId) {
    this.feedTemplateId = feedTemplateId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteFeedManagerTemplateRequest deleteFeedManagerTemplateRequest = (DeleteFeedManagerTemplateRequest) o;
    return Objects.equals(this.feedTemplateId, deleteFeedManagerTemplateRequest.feedTemplateId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feedTemplateId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteFeedManagerTemplateRequest {\n");
    sb.append("    feedTemplateId: ").append(toIndentedString(feedTemplateId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("FeedTemplateId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DeleteFeedManagerTemplateRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeleteFeedManagerTemplateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeleteFeedManagerTemplateRequest is not found in the empty JSON string", DeleteFeedManagerTemplateRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeleteFeedManagerTemplateRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeleteFeedManagerTemplateRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeleteFeedManagerTemplateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeleteFeedManagerTemplateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeleteFeedManagerTemplateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeleteFeedManagerTemplateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeleteFeedManagerTemplateRequest>() {
           @Override
           public void write(JsonWriter out, DeleteFeedManagerTemplateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeleteFeedManagerTemplateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DeleteFeedManagerTemplateRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DeleteFeedManagerTemplateRequest
  * @throws IOException if the JSON string is invalid with respect to DeleteFeedManagerTemplateRequest
  */
  public static DeleteFeedManagerTemplateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeleteFeedManagerTemplateRequest.class);
  }

 /**
  * Convert an instance of DeleteFeedManagerTemplateRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

