/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * EnhancedMarginItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class EnhancedMarginItem {
  public static final String SERIALIZED_NAME_ADJUSTMENT_TYPE = "AdjustmentType";
  @SerializedName(SERIALIZED_NAME_ADJUSTMENT_TYPE)
  private MarketMarginAdjustmentType adjustmentType;

  public static final String SERIALIZED_NAME_ADJUSTMENT_VALUE = "AdjustmentValue";
  @SerializedName(SERIALIZED_NAME_ADJUSTMENT_VALUE)
  private Double adjustmentValue;

  public static final String SERIALIZED_NAME_MARGIN_KEY = "MarginKey";
  @SerializedName(SERIALIZED_NAME_MARGIN_KEY)
  private Double marginKey;

  public EnhancedMarginItem() {
  }

  public EnhancedMarginItem adjustmentType(MarketMarginAdjustmentType adjustmentType) {
    this.adjustmentType = adjustmentType;
    return this;
  }

   /**
   * Get adjustmentType
   * @return adjustmentType
  **/
  @javax.annotation.Nullable
  public MarketMarginAdjustmentType getAdjustmentType() {
    return adjustmentType;
  }

  public void setAdjustmentType(MarketMarginAdjustmentType adjustmentType) {
    this.adjustmentType = adjustmentType;
  }


  public EnhancedMarginItem adjustmentValue(Double adjustmentValue) {
    this.adjustmentValue = adjustmentValue;
    return this;
  }

   /**
   * Get adjustmentValue
   * @return adjustmentValue
  **/
  @javax.annotation.Nullable
  public Double getAdjustmentValue() {
    return adjustmentValue;
  }

  public void setAdjustmentValue(Double adjustmentValue) {
    this.adjustmentValue = adjustmentValue;
  }


  public EnhancedMarginItem marginKey(Double marginKey) {
    this.marginKey = marginKey;
    return this;
  }

   /**
   * Get marginKey
   * @return marginKey
  **/
  @javax.annotation.Nullable
  public Double getMarginKey() {
    return marginKey;
  }

  public void setMarginKey(Double marginKey) {
    this.marginKey = marginKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnhancedMarginItem enhancedMarginItem = (EnhancedMarginItem) o;
    return Objects.equals(this.adjustmentType, enhancedMarginItem.adjustmentType) &&
        Objects.equals(this.adjustmentValue, enhancedMarginItem.adjustmentValue) &&
        Objects.equals(this.marginKey, enhancedMarginItem.marginKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adjustmentType, adjustmentValue, marginKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnhancedMarginItem {\n");
    sb.append("    adjustmentType: ").append(toIndentedString(adjustmentType)).append("\n");
    sb.append("    adjustmentValue: ").append(toIndentedString(adjustmentValue)).append("\n");
    sb.append("    marginKey: ").append(toIndentedString(marginKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AdjustmentType");
    openapiFields.add("AdjustmentValue");
    openapiFields.add("MarginKey");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EnhancedMarginItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EnhancedMarginItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EnhancedMarginItem is not found in the empty JSON string", EnhancedMarginItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EnhancedMarginItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EnhancedMarginItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `AdjustmentType`
      if (jsonObj.get("AdjustmentType") != null && !jsonObj.get("AdjustmentType").isJsonNull()) {
        MarketMarginAdjustmentType.validateJsonElement(jsonObj.get("AdjustmentType"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EnhancedMarginItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EnhancedMarginItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EnhancedMarginItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EnhancedMarginItem.class));

       return (TypeAdapter<T>) new TypeAdapter<EnhancedMarginItem>() {
           @Override
           public void write(JsonWriter out, EnhancedMarginItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EnhancedMarginItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EnhancedMarginItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EnhancedMarginItem
  * @throws IOException if the JSON string is invalid with respect to EnhancedMarginItem
  */
  public static EnhancedMarginItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EnhancedMarginItem.class);
  }

 /**
  * Convert an instance of EnhancedMarginItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

