/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * FeedManagerChampGroupChamp
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class FeedManagerChampGroupChamp {
  public static final String SERIALIZED_NAME_IS_ASSIGNED = "IsAssigned";
  @SerializedName(SERIALIZED_NAME_IS_ASSIGNED)
  private Boolean isAssigned;

  public static final String SERIALIZED_NAME_CHAMP_NAME = "ChampName";
  @SerializedName(SERIALIZED_NAME_CHAMP_NAME)
  private String champName;

  public static final String SERIALIZED_NAME_IS_ASSIGNED_IN_OTHER_GROUP = "IsAssignedInOtherGroup";
  @SerializedName(SERIALIZED_NAME_IS_ASSIGNED_IN_OTHER_GROUP)
  private Boolean isAssignedInOtherGroup;

  public static final String SERIALIZED_NAME_CHAMP_ID = "ChampId";
  @SerializedName(SERIALIZED_NAME_CHAMP_ID)
  private Integer champId;

  public FeedManagerChampGroupChamp() {
  }

  public FeedManagerChampGroupChamp isAssigned(Boolean isAssigned) {
    this.isAssigned = isAssigned;
    return this;
  }

   /**
   * Get isAssigned
   * @return isAssigned
  **/
  @javax.annotation.Nullable
  public Boolean getIsAssigned() {
    return isAssigned;
  }

  public void setIsAssigned(Boolean isAssigned) {
    this.isAssigned = isAssigned;
  }


  public FeedManagerChampGroupChamp champName(String champName) {
    this.champName = champName;
    return this;
  }

   /**
   * Get champName
   * @return champName
  **/
  @javax.annotation.Nullable
  public String getChampName() {
    return champName;
  }

  public void setChampName(String champName) {
    this.champName = champName;
  }


  public FeedManagerChampGroupChamp isAssignedInOtherGroup(Boolean isAssignedInOtherGroup) {
    this.isAssignedInOtherGroup = isAssignedInOtherGroup;
    return this;
  }

   /**
   * Get isAssignedInOtherGroup
   * @return isAssignedInOtherGroup
  **/
  @javax.annotation.Nullable
  public Boolean getIsAssignedInOtherGroup() {
    return isAssignedInOtherGroup;
  }

  public void setIsAssignedInOtherGroup(Boolean isAssignedInOtherGroup) {
    this.isAssignedInOtherGroup = isAssignedInOtherGroup;
  }


  public FeedManagerChampGroupChamp champId(Integer champId) {
    this.champId = champId;
    return this;
  }

   /**
   * Get champId
   * @return champId
  **/
  @javax.annotation.Nullable
  public Integer getChampId() {
    return champId;
  }

  public void setChampId(Integer champId) {
    this.champId = champId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedManagerChampGroupChamp feedManagerChampGroupChamp = (FeedManagerChampGroupChamp) o;
    return Objects.equals(this.isAssigned, feedManagerChampGroupChamp.isAssigned) &&
        Objects.equals(this.champName, feedManagerChampGroupChamp.champName) &&
        Objects.equals(this.isAssignedInOtherGroup, feedManagerChampGroupChamp.isAssignedInOtherGroup) &&
        Objects.equals(this.champId, feedManagerChampGroupChamp.champId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(isAssigned, champName, isAssignedInOtherGroup, champId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedManagerChampGroupChamp {\n");
    sb.append("    isAssigned: ").append(toIndentedString(isAssigned)).append("\n");
    sb.append("    champName: ").append(toIndentedString(champName)).append("\n");
    sb.append("    isAssignedInOtherGroup: ").append(toIndentedString(isAssignedInOtherGroup)).append("\n");
    sb.append("    champId: ").append(toIndentedString(champId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("IsAssigned");
    openapiFields.add("ChampName");
    openapiFields.add("IsAssignedInOtherGroup");
    openapiFields.add("ChampId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to FeedManagerChampGroupChamp
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FeedManagerChampGroupChamp.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FeedManagerChampGroupChamp is not found in the empty JSON string", FeedManagerChampGroupChamp.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FeedManagerChampGroupChamp.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FeedManagerChampGroupChamp` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("ChampName") != null && !jsonObj.get("ChampName").isJsonNull()) && !jsonObj.get("ChampName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ChampName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ChampName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FeedManagerChampGroupChamp.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FeedManagerChampGroupChamp' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FeedManagerChampGroupChamp> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FeedManagerChampGroupChamp.class));

       return (TypeAdapter<T>) new TypeAdapter<FeedManagerChampGroupChamp>() {
           @Override
           public void write(JsonWriter out, FeedManagerChampGroupChamp value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FeedManagerChampGroupChamp read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FeedManagerChampGroupChamp given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FeedManagerChampGroupChamp
  * @throws IOException if the JSON string is invalid with respect to FeedManagerChampGroupChamp
  */
  public static FeedManagerChampGroupChamp fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FeedManagerChampGroupChamp.class);
  }

 /**
  * Convert an instance of FeedManagerChampGroupChamp to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

