/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.util.*;

/**
 * FeedReportConfigSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class FeedReportConfigSummary {
  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_FEED_SUMMARIES = "FeedSummaries";
  @SerializedName(SERIALIZED_NAME_FEED_SUMMARIES)
  private List<FeedReportSourceSummary> feedSummaries;

  public static final String SERIALIZED_NAME_LIVE_COUNT = "LiveCount";
  @SerializedName(SERIALIZED_NAME_LIVE_COUNT)
  private Integer liveCount;

  public static final String SERIALIZED_NAME_PRELIVE_COUNT = "PreliveCount";
  @SerializedName(SERIALIZED_NAME_PRELIVE_COUNT)
  private Integer preliveCount;

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "TotalCount";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  private Integer totalCount;

  public static final String SERIALIZED_NAME_CONFIG_ID = "ConfigId";
  @SerializedName(SERIALIZED_NAME_CONFIG_ID)
  private Integer configId;

  public FeedReportConfigSummary() {
  }

  public FeedReportConfigSummary(
     Integer liveCount, 
     Integer preliveCount, 
     Integer totalCount
  ) {
    this();
    this.liveCount = liveCount;
    this.preliveCount = preliveCount;
    this.totalCount = totalCount;
  }

  public FeedReportConfigSummary name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public FeedReportConfigSummary feedSummaries(List<FeedReportSourceSummary> feedSummaries) {
    this.feedSummaries = feedSummaries;
    return this;
  }

  public FeedReportConfigSummary addFeedSummariesItem(FeedReportSourceSummary feedSummariesItem) {
    if (this.feedSummaries == null) {
      this.feedSummaries = new ArrayList<>();
    }
    this.feedSummaries.add(feedSummariesItem);
    return this;
  }

   /**
   * Get feedSummaries
   * @return feedSummaries
  **/
  @javax.annotation.Nullable
  public List<FeedReportSourceSummary> getFeedSummaries() {
    return feedSummaries;
  }

  public void setFeedSummaries(List<FeedReportSourceSummary> feedSummaries) {
    this.feedSummaries = feedSummaries;
  }


   /**
   * Get liveCount
   * @return liveCount
  **/
  @javax.annotation.Nullable
  public Integer getLiveCount() {
    return liveCount;
  }



   /**
   * Get preliveCount
   * @return preliveCount
  **/
  @javax.annotation.Nullable
  public Integer getPreliveCount() {
    return preliveCount;
  }



   /**
   * Get totalCount
   * @return totalCount
  **/
  @javax.annotation.Nullable
  public Integer getTotalCount() {
    return totalCount;
  }



  public FeedReportConfigSummary configId(Integer configId) {
    this.configId = configId;
    return this;
  }

   /**
   * Get configId
   * @return configId
  **/
  @javax.annotation.Nullable
  public Integer getConfigId() {
    return configId;
  }

  public void setConfigId(Integer configId) {
    this.configId = configId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedReportConfigSummary feedReportConfigSummary = (FeedReportConfigSummary) o;
    return Objects.equals(this.name, feedReportConfigSummary.name) &&
        Objects.equals(this.feedSummaries, feedReportConfigSummary.feedSummaries) &&
        Objects.equals(this.liveCount, feedReportConfigSummary.liveCount) &&
        Objects.equals(this.preliveCount, feedReportConfigSummary.preliveCount) &&
        Objects.equals(this.totalCount, feedReportConfigSummary.totalCount) &&
        Objects.equals(this.configId, feedReportConfigSummary.configId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, feedSummaries, liveCount, preliveCount, totalCount, configId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedReportConfigSummary {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    feedSummaries: ").append(toIndentedString(feedSummaries)).append("\n");
    sb.append("    liveCount: ").append(toIndentedString(liveCount)).append("\n");
    sb.append("    preliveCount: ").append(toIndentedString(preliveCount)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    configId: ").append(toIndentedString(configId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Name");
    openapiFields.add("FeedSummaries");
    openapiFields.add("LiveCount");
    openapiFields.add("PreliveCount");
    openapiFields.add("TotalCount");
    openapiFields.add("ConfigId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to FeedReportConfigSummary
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FeedReportConfigSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FeedReportConfigSummary is not found in the empty JSON string", FeedReportConfigSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FeedReportConfigSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FeedReportConfigSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) && !jsonObj.get("Name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Name").toString()));
      }
      if (jsonObj.get("FeedSummaries") != null && !jsonObj.get("FeedSummaries").isJsonNull()) {
        JsonArray jsonArrayfeedSummaries = jsonObj.getAsJsonArray("FeedSummaries");
        if (jsonArrayfeedSummaries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("FeedSummaries").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `FeedSummaries` to be an array in the JSON string but got `%s`", jsonObj.get("FeedSummaries").toString()));
          }

          // validate the optional field `FeedSummaries` (array)
          for (int i = 0; i < jsonArrayfeedSummaries.size(); i++) {
            FeedReportSourceSummary.validateJsonElement(jsonArrayfeedSummaries.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FeedReportConfigSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FeedReportConfigSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FeedReportConfigSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FeedReportConfigSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<FeedReportConfigSummary>() {
           @Override
           public void write(JsonWriter out, FeedReportConfigSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FeedReportConfigSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FeedReportConfigSummary given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FeedReportConfigSummary
  * @throws IOException if the JSON string is invalid with respect to FeedReportConfigSummary
  */
  public static FeedReportConfigSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FeedReportConfigSummary.class);
  }

 /**
  * Convert an instance of FeedReportConfigSummary to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

