/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.*;

/**
 * MarketSettlementOperationItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class MarketSettlementOperationItem {
  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private MarketSettlementStatusesEnum status;

  public static final String SERIALIZED_NAME_OPERATION_ID = "OperationId";
  @SerializedName(SERIALIZED_NAME_OPERATION_ID)
  private UUID operationId;

  public MarketSettlementOperationItem() {
  }

  public MarketSettlementOperationItem status(MarketSettlementStatusesEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  public MarketSettlementStatusesEnum getStatus() {
    return status;
  }

  public void setStatus(MarketSettlementStatusesEnum status) {
    this.status = status;
  }


  public MarketSettlementOperationItem operationId(UUID operationId) {
    this.operationId = operationId;
    return this;
  }

   /**
   * Get operationId
   * @return operationId
  **/
  @javax.annotation.Nullable
  public UUID getOperationId() {
    return operationId;
  }

  public void setOperationId(UUID operationId) {
    this.operationId = operationId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketSettlementOperationItem marketSettlementOperationItem = (MarketSettlementOperationItem) o;
    return Objects.equals(this.status, marketSettlementOperationItem.status) &&
        Objects.equals(this.operationId, marketSettlementOperationItem.operationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, operationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketSettlementOperationItem {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    operationId: ").append(toIndentedString(operationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Status");
    openapiFields.add("OperationId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to MarketSettlementOperationItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MarketSettlementOperationItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MarketSettlementOperationItem is not found in the empty JSON string", MarketSettlementOperationItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MarketSettlementOperationItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MarketSettlementOperationItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `Status`
      if (jsonObj.get("Status") != null && !jsonObj.get("Status").isJsonNull()) {
        MarketSettlementStatusesEnum.validateJsonElement(jsonObj.get("Status"));
      }
      if ((jsonObj.get("OperationId") != null && !jsonObj.get("OperationId").isJsonNull()) && !jsonObj.get("OperationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `OperationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("OperationId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MarketSettlementOperationItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MarketSettlementOperationItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MarketSettlementOperationItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MarketSettlementOperationItem.class));

       return (TypeAdapter<T>) new TypeAdapter<MarketSettlementOperationItem>() {
           @Override
           public void write(JsonWriter out, MarketSettlementOperationItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MarketSettlementOperationItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MarketSettlementOperationItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MarketSettlementOperationItem
  * @throws IOException if the JSON string is invalid with respect to MarketSettlementOperationItem
  */
  public static MarketSettlementOperationItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MarketSettlementOperationItem.class);
  }

 /**
  * Convert an instance of MarketSettlementOperationItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

