/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets NightSoftWinningsViolationActions
 */
@JsonAdapter(NightSoftWinningsViolationActions.Adapter.class)
public enum NightSoftWinningsViolationActions {
  
  MarkPending(0),
  
  AutoAdjustStake(1),
  
  AdjustStakeAndAsk(2),
  
  PartiallyPending(3),
  
  PartiallyAcceptRejectAndAsk(4);

  private Integer value;

  NightSoftWinningsViolationActions(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static NightSoftWinningsViolationActions fromValue(Integer value) {
    for (NightSoftWinningsViolationActions b : NightSoftWinningsViolationActions.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<NightSoftWinningsViolationActions> {
    @Override
    public void write(final JsonWriter jsonWriter, final NightSoftWinningsViolationActions enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public NightSoftWinningsViolationActions read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return NightSoftWinningsViolationActions.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    Integer value = jsonElement.getAsInt();
    NightSoftWinningsViolationActions.fromValue(value);
  }
}

