/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * ResetPendingSelectionRequestItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class ResetPendingSelectionRequestItem {
  public static final String SERIALIZED_NAME_PENDING_RESULT = "PendingResult";
  @SerializedName(SERIALIZED_NAME_PENDING_RESULT)
  private SelectionResults pendingResult;

  public static final String SERIALIZED_NAME_SELECTION_ID = "SelectionId";
  @SerializedName(SERIALIZED_NAME_SELECTION_ID)
  private Long selectionId;

  public ResetPendingSelectionRequestItem() {
  }

  public ResetPendingSelectionRequestItem pendingResult(SelectionResults pendingResult) {
    this.pendingResult = pendingResult;
    return this;
  }

   /**
   * Get pendingResult
   * @return pendingResult
  **/
  @javax.annotation.Nullable
  public SelectionResults getPendingResult() {
    return pendingResult;
  }

  public void setPendingResult(SelectionResults pendingResult) {
    this.pendingResult = pendingResult;
  }


  public ResetPendingSelectionRequestItem selectionId(Long selectionId) {
    this.selectionId = selectionId;
    return this;
  }

   /**
   * Get selectionId
   * @return selectionId
  **/
  @javax.annotation.Nullable
  public Long getSelectionId() {
    return selectionId;
  }

  public void setSelectionId(Long selectionId) {
    this.selectionId = selectionId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResetPendingSelectionRequestItem resetPendingSelectionRequestItem = (ResetPendingSelectionRequestItem) o;
    return Objects.equals(this.pendingResult, resetPendingSelectionRequestItem.pendingResult) &&
        Objects.equals(this.selectionId, resetPendingSelectionRequestItem.selectionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pendingResult, selectionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResetPendingSelectionRequestItem {\n");
    sb.append("    pendingResult: ").append(toIndentedString(pendingResult)).append("\n");
    sb.append("    selectionId: ").append(toIndentedString(selectionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("PendingResult");
    openapiFields.add("SelectionId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ResetPendingSelectionRequestItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResetPendingSelectionRequestItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResetPendingSelectionRequestItem is not found in the empty JSON string", ResetPendingSelectionRequestItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResetPendingSelectionRequestItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResetPendingSelectionRequestItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `PendingResult`
      if (jsonObj.get("PendingResult") != null && !jsonObj.get("PendingResult").isJsonNull()) {
        SelectionResults.validateJsonElement(jsonObj.get("PendingResult"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResetPendingSelectionRequestItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResetPendingSelectionRequestItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResetPendingSelectionRequestItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResetPendingSelectionRequestItem.class));

       return (TypeAdapter<T>) new TypeAdapter<ResetPendingSelectionRequestItem>() {
           @Override
           public void write(JsonWriter out, ResetPendingSelectionRequestItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResetPendingSelectionRequestItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ResetPendingSelectionRequestItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ResetPendingSelectionRequestItem
  * @throws IOException if the JSON string is invalid with respect to ResetPendingSelectionRequestItem
  */
  public static ResetPendingSelectionRequestItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResetPendingSelectionRequestItem.class);
  }

 /**
  * Convert an instance of ResetPendingSelectionRequestItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

