/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * SaveDistributionCodesRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class SaveDistributionCodesRequest {
  public static final String SERIALIZED_NAME_FREE_PLAN_AMOUNT = "FreePlanAmount";
  @SerializedName(SERIALIZED_NAME_FREE_PLAN_AMOUNT)
  private Double freePlanAmount;

  public static final String SERIALIZED_NAME_BONUS_CAMPAIGN_ID = "BonusCampaignId";
  @SerializedName(SERIALIZED_NAME_BONUS_CAMPAIGN_ID)
  private Integer bonusCampaignId;

  public SaveDistributionCodesRequest() {
  }

  public SaveDistributionCodesRequest freePlanAmount(Double freePlanAmount) {
    this.freePlanAmount = freePlanAmount;
    return this;
  }

   /**
   * Get freePlanAmount
   * @return freePlanAmount
  **/
  @javax.annotation.Nullable
  public Double getFreePlanAmount() {
    return freePlanAmount;
  }

  public void setFreePlanAmount(Double freePlanAmount) {
    this.freePlanAmount = freePlanAmount;
  }


  public SaveDistributionCodesRequest bonusCampaignId(Integer bonusCampaignId) {
    this.bonusCampaignId = bonusCampaignId;
    return this;
  }

   /**
   * Get bonusCampaignId
   * @return bonusCampaignId
  **/
  @javax.annotation.Nullable
  public Integer getBonusCampaignId() {
    return bonusCampaignId;
  }

  public void setBonusCampaignId(Integer bonusCampaignId) {
    this.bonusCampaignId = bonusCampaignId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaveDistributionCodesRequest saveDistributionCodesRequest = (SaveDistributionCodesRequest) o;
    return Objects.equals(this.freePlanAmount, saveDistributionCodesRequest.freePlanAmount) &&
        Objects.equals(this.bonusCampaignId, saveDistributionCodesRequest.bonusCampaignId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(freePlanAmount, bonusCampaignId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaveDistributionCodesRequest {\n");
    sb.append("    freePlanAmount: ").append(toIndentedString(freePlanAmount)).append("\n");
    sb.append("    bonusCampaignId: ").append(toIndentedString(bonusCampaignId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("FreePlanAmount");
    openapiFields.add("BonusCampaignId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SaveDistributionCodesRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SaveDistributionCodesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SaveDistributionCodesRequest is not found in the empty JSON string", SaveDistributionCodesRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SaveDistributionCodesRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SaveDistributionCodesRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SaveDistributionCodesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SaveDistributionCodesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SaveDistributionCodesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SaveDistributionCodesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SaveDistributionCodesRequest>() {
           @Override
           public void write(JsonWriter out, SaveDistributionCodesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SaveDistributionCodesRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SaveDistributionCodesRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SaveDistributionCodesRequest
  * @throws IOException if the JSON string is invalid with respect to SaveDistributionCodesRequest
  */
  public static SaveDistributionCodesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SaveDistributionCodesRequest.class);
  }

 /**
  * Convert an instance of SaveDistributionCodesRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

