/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * SportMarketGroupMarketChildUpdateRequestItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class SportMarketGroupMarketChildUpdateRequestItem {
  public static final String SERIALIZED_NAME_MARKET_TYPE_ID = "MarketTypeId";
  @SerializedName(SERIALIZED_NAME_MARKET_TYPE_ID)
  private Integer marketTypeId;

  public SportMarketGroupMarketChildUpdateRequestItem() {
  }

  public SportMarketGroupMarketChildUpdateRequestItem marketTypeId(Integer marketTypeId) {
    this.marketTypeId = marketTypeId;
    return this;
  }

   /**
   * Get marketTypeId
   * @return marketTypeId
  **/
  @javax.annotation.Nullable
  public Integer getMarketTypeId() {
    return marketTypeId;
  }

  public void setMarketTypeId(Integer marketTypeId) {
    this.marketTypeId = marketTypeId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SportMarketGroupMarketChildUpdateRequestItem sportMarketGroupMarketChildUpdateRequestItem = (SportMarketGroupMarketChildUpdateRequestItem) o;
    return Objects.equals(this.marketTypeId, sportMarketGroupMarketChildUpdateRequestItem.marketTypeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(marketTypeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SportMarketGroupMarketChildUpdateRequestItem {\n");
    sb.append("    marketTypeId: ").append(toIndentedString(marketTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MarketTypeId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SportMarketGroupMarketChildUpdateRequestItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SportMarketGroupMarketChildUpdateRequestItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SportMarketGroupMarketChildUpdateRequestItem is not found in the empty JSON string", SportMarketGroupMarketChildUpdateRequestItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SportMarketGroupMarketChildUpdateRequestItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SportMarketGroupMarketChildUpdateRequestItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SportMarketGroupMarketChildUpdateRequestItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SportMarketGroupMarketChildUpdateRequestItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SportMarketGroupMarketChildUpdateRequestItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SportMarketGroupMarketChildUpdateRequestItem.class));

       return (TypeAdapter<T>) new TypeAdapter<SportMarketGroupMarketChildUpdateRequestItem>() {
           @Override
           public void write(JsonWriter out, SportMarketGroupMarketChildUpdateRequestItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SportMarketGroupMarketChildUpdateRequestItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SportMarketGroupMarketChildUpdateRequestItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SportMarketGroupMarketChildUpdateRequestItem
  * @throws IOException if the JSON string is invalid with respect to SportMarketGroupMarketChildUpdateRequestItem
  */
  public static SportMarketGroupMarketChildUpdateRequestItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SportMarketGroupMarketChildUpdateRequestItem.class);
  }

 /**
  * Convert an instance of SportMarketGroupMarketChildUpdateRequestItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

