/*
 * Backoffice.Api
 * Backoffice.Api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package BackofficeGenerator.model;

import BackofficeGenerator.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * UpdateBoundsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-26T23:02:24.556418400+03:00[Europe/Moscow]")
public class UpdateBoundsRequest {
  public static final String SERIALIZED_NAME_NEW_LOW_BOUND = "NewLowBound";
  @SerializedName(SERIALIZED_NAME_NEW_LOW_BOUND)
  private Integer newLowBound;

  public static final String SERIALIZED_NAME_NEW_UPPER_BOUND = "NewUpperBound";
  @SerializedName(SERIALIZED_NAME_NEW_UPPER_BOUND)
  private Integer newUpperBound;

  public static final String SERIALIZED_NAME_NEW_BONUS_VALUE = "NewBonusValue";
  @SerializedName(SERIALIZED_NAME_NEW_BONUS_VALUE)
  private Double newBonusValue;

  public static final String SERIALIZED_NAME_BONUS_BOUNDS_ID = "BonusBoundsId";
  @SerializedName(SERIALIZED_NAME_BONUS_BOUNDS_ID)
  private Integer bonusBoundsId;

  public UpdateBoundsRequest() {
  }

  public UpdateBoundsRequest newLowBound(Integer newLowBound) {
    this.newLowBound = newLowBound;
    return this;
  }

   /**
   * Get newLowBound
   * @return newLowBound
  **/
  @javax.annotation.Nullable
  public Integer getNewLowBound() {
    return newLowBound;
  }

  public void setNewLowBound(Integer newLowBound) {
    this.newLowBound = newLowBound;
  }


  public UpdateBoundsRequest newUpperBound(Integer newUpperBound) {
    this.newUpperBound = newUpperBound;
    return this;
  }

   /**
   * Get newUpperBound
   * @return newUpperBound
  **/
  @javax.annotation.Nullable
  public Integer getNewUpperBound() {
    return newUpperBound;
  }

  public void setNewUpperBound(Integer newUpperBound) {
    this.newUpperBound = newUpperBound;
  }


  public UpdateBoundsRequest newBonusValue(Double newBonusValue) {
    this.newBonusValue = newBonusValue;
    return this;
  }

   /**
   * Get newBonusValue
   * @return newBonusValue
  **/
  @javax.annotation.Nullable
  public Double getNewBonusValue() {
    return newBonusValue;
  }

  public void setNewBonusValue(Double newBonusValue) {
    this.newBonusValue = newBonusValue;
  }


  public UpdateBoundsRequest bonusBoundsId(Integer bonusBoundsId) {
    this.bonusBoundsId = bonusBoundsId;
    return this;
  }

   /**
   * Get bonusBoundsId
   * @return bonusBoundsId
  **/
  @javax.annotation.Nullable
  public Integer getBonusBoundsId() {
    return bonusBoundsId;
  }

  public void setBonusBoundsId(Integer bonusBoundsId) {
    this.bonusBoundsId = bonusBoundsId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateBoundsRequest updateBoundsRequest = (UpdateBoundsRequest) o;
    return Objects.equals(this.newLowBound, updateBoundsRequest.newLowBound) &&
        Objects.equals(this.newUpperBound, updateBoundsRequest.newUpperBound) &&
        Objects.equals(this.newBonusValue, updateBoundsRequest.newBonusValue) &&
        Objects.equals(this.bonusBoundsId, updateBoundsRequest.bonusBoundsId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newLowBound, newUpperBound, newBonusValue, bonusBoundsId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateBoundsRequest {\n");
    sb.append("    newLowBound: ").append(toIndentedString(newLowBound)).append("\n");
    sb.append("    newUpperBound: ").append(toIndentedString(newUpperBound)).append("\n");
    sb.append("    newBonusValue: ").append(toIndentedString(newBonusValue)).append("\n");
    sb.append("    bonusBoundsId: ").append(toIndentedString(bonusBoundsId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("NewLowBound");
    openapiFields.add("NewUpperBound");
    openapiFields.add("NewBonusValue");
    openapiFields.add("BonusBoundsId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UpdateBoundsRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateBoundsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateBoundsRequest is not found in the empty JSON string", UpdateBoundsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateBoundsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateBoundsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateBoundsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateBoundsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateBoundsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateBoundsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateBoundsRequest>() {
           @Override
           public void write(JsonWriter out, UpdateBoundsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateBoundsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdateBoundsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdateBoundsRequest
  * @throws IOException if the JSON string is invalid with respect to UpdateBoundsRequest
  */
  public static UpdateBoundsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateBoundsRequest.class);
  }

 /**
  * Convert an instance of UpdateBoundsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

